### ISSUE TITLE
Tracking: Launchpad: Desired Documentation Improvements

### ISSUE THREAD

**Issue by chriswessels** [graphops/docs#72]
- [x] A section describing which blockchains are officially supported by GraphOps
- [x] A section describing how a user can use Launchpad to deploy "unsupported chains"/custom releases
- [x] A section describing stable vs canary release channels and how versions move through them
- [x] Examples of following stable, following canary, and running a custom image tag
- [x] A section describing the different ways to use launchpad (without starter, without helmfile)
